version: '3.8'

services:
  chat-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: chat-app-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - APP_URL=${APP_URL:-http://localhost}
      - API_GATEWAY_URL=${API_GATEWAY_URL:-http://localhost:3000}
    networks:
      - chat-app-network

networks:
  chat-app-network:
    driver: bridge
