server:
  port: 9080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}

services:
  user-service:
    url: ${USER_SERVICE_URL:http://user-service:8081}
  websocket-service:
    url: ${WEBSOCKET_SERVICE_URL:http://websocket-service:8082}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.chatapp.gateway: DEBUG