server:
  port: 8081

spring:
  application:
    name: user-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    write:
      url: ${DB_WRITE_URL:jdbc:mysql://mysql:3306/chatapp_users?useSSL=false&allowPublicKeyRetrieval=true}
      username: ${DB_WRITE_USERNAME:chatapp}
      password: ${DB_WRITE_PASSWORD:chatapp123}
      driver-class-name: com.mysql.cj.jdbc.Driver
    read:
      url: ${DB_READ_URL:jdbc:mysql://mysql:3306/chatapp_users?useSSL=false&allowPublicKeyRetrieval=true}
      username: ${DB_READ_USERNAME:chatapp}
      password: ${DB_READ_PASSWORD:chatapp123}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    packages-to-scan: com.chatapp.userservice.model
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 900000 # 15 minutes
  refresh-expiration: 604800000 # 7 days

logging:
  level:
    com.chatapp.userservice: DEBUG
    org.springframework.security: DEBUG